# Default configuration shared between jobs
defaults: &defaults
  working_directory: ~/docker-cld3-wasm
  docker:
  - image: circleci/golang:1.10.3-stretch-browsers

version: 2
jobs:
  # Jobs for building wasm binary for cld3
  build:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Generate build artifact folder
          command: mkdir -p ~/build

      - run:
          name: Build docker image for wasm cld3
          command: |
            BRANCH=master
            TARGET=wasm
            # Build docker image, specify commit sha of cld3
            docker build -t cld3-wasm_0.1.$CIRCLE_BUILD_NUM --build-arg BRANCH=$BRANCH --build-arg TARGET=$TARGET .
      - run:
          name: Build wasm binary
          command: |
            # Run built docker image
            docker run --name cld3-wasm -t cld3-wasm_0.1.$CIRCLE_BUILD_NUM /bin/bash -l -c "./build.sh -o /out/cld3.js"
            # Copy build output
            docker cp cld3-wasm:/out ~/build
      - run:
          name: Build asm.js binary
          command: |
            # Run built docker image
            docker run --name cld3-asm -t cld3-wasm_0.1.$CIRCLE_BUILD_NUM /bin/bash -l -c "./build.sh -o /out/cld3-asm.js -s WASM=0"
            # Copy build output
            docker cp cld3-asm:/out ~/build
      - run:
          working_directory: ~/build
          name: Copy artifacts
          command: |
            # File copied from docker container has root access only, modify permission
            sudo chmod -R go+wr ~/build
            # https://github.com/kwonoj/docker-hunspell-wasm/issues/63
            for filename in ./out/*.js; do
              sed -i 's/throw new Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compile-time option (for example, -s ENVIRONMENT=web or -s ENVIRONMENT=node)")/const ISNODE = Module["ENVIRONMENT"] === "NODE";ENVIRONMENT_IS_NODE = ISNODE;ENVIRONMENT_IS_WEB = !ISNODE;/g' $filename
            done

            # Generate hash
            for filename in ./out/*; do
              sha512sum $filename > $filename.sha512
            done

            # Generate archive for convinience
            tar -zcvf ./cld3-asm-$(echo $CIRCLE_SHA1 | cut -c -7).tar.gz out
            # Flatten file out path
            mv ./out/* ./ && rm -rf ./out
      # Upload artifact into CircleCi artifacts
      - store_artifacts:
          path: ~/build
          destination: build
      # Persist build results to share between different jobs
      - persist_to_workspace:
          root: ~/build
          paths:
            - ./*

  # Jobs to create github release for tagged build
  release:
    <<: *defaults
    steps:
      # Acquire persisted build results
      - attach_workspace:
          at: ~/build
      - run:
          name: Create Release
          command: |
            go get github.com/tcnksm/ghr
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $CIRCLE_TAG ~/build

workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          # Filter jobs to run on tag only
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - build
